### ISSUE TITLE
No sources available

### ISSUE THREAD

**Issue by tokee** [kb-dk/kb-util#13]
Don't know how it works, but IntelliJ IDEA is normally capable of downloading the sources when using a dependency. Not so for `kb-util`. We should fix this.

**Comment by sbktc** [comment]
The artifacts are uploaded to the sbforge nexus server, and both sources and javadoc are available, see for instance the v1.3.0 release: https://sbforge.org/nexus/content/repositories/releases/dk/kb/util/kb-util/1.3.0/
I suppose it boils down to an issue with IntelliJ. Is it able to resolve sources and javadoc from other projects with artifacts only available on sbforge.org/nexus?

**Comment by tokee** [comment]
I tried with the new version 1.4.0 and it worked fine. Pixies I guess. Closing now.
